cloudnative-pg/cloudnative-pg.github.io

- content/end_users/_index.md
- content/support/_index.md
- content/support/edb.md
- layouts/_default/single.html
- layouts/paged_content/list.html
Create paged_content layout to allow for supprt & end user pages to be generated from md file per entity
> feat: paged layout for end users and support pages

- layouts/_default/baseof.html
- layouts/partials/nav.html
> feat: add number of Github stars

- layouts/partials/nav.html
> fix: use invitation link for Slack

- layouts/index.html
> fix: use "originally created"

- layouts/partials/footer.html
> Add PostgreSQL trademark notice in the footer

- assets/css/style.css
- layouts/blog/list.html
- layouts/partials/author_sidebar.html
- layouts/partials/blog_datetime.html
- layouts/partials/blog_sidebar.html
- Fixed tag margin.
- Fixed blog profile details vertical alignment.
> Blog page UI fixes

- assets/documentation/1.15.0/installation_upgrade/index.html
> fix: URL to charts

- layouts/index.html
> doc: add link to EDB in the home page

- content/info/high-availability.md
> add missing line

- content/blog/cloudnative-pg-1-16-0-released/index.md
> fix: typo in release announcement

- config.toml
> fix: title metadata

- layouts/blog/single.html
Closes #71
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>
> fix: remove `w-full` from blog post image

- .github/workflows/hugo_build.yml
Closes #74
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>
> chore: update Hugo version to 0.101.0

- content/docs/_index.md
Correct "dificiencies" to "deficiencies" 😄 
Signed-off-by: bb-transpower <104113947+bb-transpower@users.noreply.github.com>
> Fix a spelling error

- content/docs/_index.md
> doc: add link to current doc version

- README.md
> doc: explain documentation process

- assets/css/style.css
- layouts/blog/list.html
- layouts/blog/single.html
> fix: mobile layout

- assets/css/style.css
- layouts/_default/single.html
- layouts/docs/section.html
This patch improves the layout of the menu bar in mobile devices. The documentation page layout have been fixed too.
> fix: mobile layout improvements

- layouts/authors/single.html
Closes #134 
Follows Tamara's fixes to the individual blog pages in #132 
See fixed page:
> fix: mobile layout of author page

- content/blog/running-postgresql-the-kubernetes-way/index.md
- layouts/partials/nav.html
Added a link with a never expire option to not have this issue in the future
> chore: fix slack invitation link

- assets/documentation/preview/README.txt
- assets/robots.txt
- hack/import_docs.sh
Add the '/preview/' directory for the latest RC version.
Add the version of CNPG on left sidebar.
Closes #204
> docs: detect RC versions as preview

- content/docs/1.22.md
- content/docs/1.24.md
- content/releases/cloudnative-pg-1-24.0-released/index.md
> docs: announce 1.24.0

- content/support/_index.md
- content/support/edb.md
> docs: adopt new commercial support policies

- assets/support/logo/dalibo.svg
- content/support/dalibo.md
> docs: add Dalibo to the list of CNPG support companies

- layouts/partials/nav.html
> docs: fix slack invite

- content/footer/footer.md
- layouts/partials/footer.html
> feat(ip): Assign copyright to the Linux Foundation

- content/releases/cloudnative-pg-1-25.1-released/index.md
- layouts/partials/nav.html
> chore: update slack link, make perpetual

- layouts/_default/baseof.html
> feat: remove Fathom

- README.md
- content/blog/running-postgresql-the-kubernetes-way/index.md
- content/releases/cloudnative-pg-1-23.0-released/index.md
- content/releases/cloudnative-pg-1-24.0-rc1-released/index.md
- content/releases/cloudnative-pg-1-24.0-released/index.md
- content/releases/cloudnative-pg-1-24.1-released/index.md
- content/releases/cloudnative-pg-1-25.0-rc1-released/index.md
- content/releases/cloudnative-pg-1-25.0-released/index.md
- content/releases/cloudnative-pg-1-25.1-released/index.md
- layouts/partials/nav.html
Also, the links on every blog post was updated
> feat: update the Slack channel to point to the CNCF Slack
